### ISSUE TITLE
Ingress pathType should be configurable

### ISSUE THREAD

**Issue by xsvil** [questdb/questdb-kubernetes#154]
### **Description:**
The current Helm chart contains hardcoded pathType for ingress paths, set to "ImplementationSpecific". This limits flexibility and adaptability to different deployment scenarios, particularly when deploying in environments that require a specific pathType (such as "Prefix" or "Exact").

### **Environment:**
Kubernetes Version: v1.2.9
Chart Name: questdb

### **Expected Behavior:**
Users should be able to specify a pathType for each ingress path directly in the values.yaml file, allowing for customized ingress behavior based on the deployment needs.

### **Actual Behavior:**
The pathType is currently hardcoded and not configurable, which can lead to suboptimal configurations in environments with specific ingress requirements. For example when using ALB controller and hardcoded values the UI is not reachable.

### **Proposed Solution:**
Modify the Helm template to include a configurable pathType per ingress path. This change will allow to define the desired pathType in the values.yaml file. Example:

```
ingress:
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
``` 

### **Willingness to Contribute:**
I am willing to work on this issue and submit a pull request with the necessary changes. I look forward to feedback and any specific requirements or suggestions.

**Comment by sklarsa** [comment]
Thanks for opening the issue! We try to make this helm chart as flexible as possible, so if you have any changes that you can make to help it run in your environment, we'd happily review a PR and incorporate the changes

**Comment by sklarsa** [comment]
chart version 0.40.2 should now be available to download and use
