### ISSUE TITLE
Upgrade networking.k8s.io/v1beta1 to networking.k8s.io/v1 Ingress

### ISSUE THREAD

**Issue by spxie85** [questdb/questdb-kubernetes#27]
Performing helm install on kubernetes v1.20.2 results in the following warnings.

W0616 11:57:59.071254    2773 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by bsmth** [comment]
Thanks @spxie85, looks like this is set in https://github.com/questdb/questdb-kubernetes/blob/master/charts/questdb/templates/ingress.yaml#L5
