### ISSUE TITLE
Expose Health Status 

### ISSUE THREAD

**Issue by djworth** [questdb/questdb-kubernetes#32]
https://questdb.io/docs/operations/health-monitoring/#configuration

Based on the documentation it looks like you can check the status of the database via port 9003 but that's doesn't seem to be exposed via the helm chart

**Comment by bsmth** [comment]
Hi Dan, thanks for pointing this out and sorry for the late reply, we've improved Prometheus compatibility in https://github.com/questdb/questdb/releases/tag/6.1.3 so this looks like a good idea 👍🏻
