### ISSUE TITLE
Add support for Helm Hub and Arftifactory Hub as distribution targets

### ISSUE THREAD

**Issue by solidnerd** [questdb/questdb-kubernetes#6]
Hey at all,
I think we could improve also the downloads of this helm chart. During under the current circumstances the stable repo 

## Phase 1

1. Create a place where your Helm chart can live for a longer time. 
    Probably a good idea is to use Github Pages for this case.
2. Publish your Helm Chart with an Automatic Workflow to your GitHub pages account.

For more information have a look at https://helm.sh/docs/topics/chart_repository/#github-pages-example

## Phase 2
Publishing your Helm Repositories to popular places.

### Helm Hub
[Helm Hub](https://hub.helm.sh)
1. Do a Pull Request on https://github.com/helm/hub for contributing the questdb helm repo

### Artifact Hub
The [Artifact Hub](https://https://artifacthub.io) is another place you can list your repos. To do that, you login (or create an account), create an organization, and list your repository. You can link it to a user or organization.

**Comment by mpsq** [comment]
I agree with you, the visibility of our chart is not great, adding it to Helm Hub is a great idea. 
I will look into this soon and keep this issue updated ;)

**Comment by mpsq** [comment]
Update on this:

## Phase 1:
Done. Documentation updated too, the PR is now pending.

## Phase 2:
Currently working on it.

**Comment by mpsq** [comment]
Update:

1.
A PR is pending for Helm Hub: https://github.com/helm/hub/pull/445

2.
https://artifacthub.io is currently processing our repository.

I will close this issue when both are finished.

**Comment by mpsq** [comment]
see previous comment
